name: DOCUMENTATION

# This workflow generates API documentation for the quantstats_lumi package using pdoc.
# pdoc is a tool that automatically creates API documentation from Python docstrings.
# The generated documentation provides a comprehensive reference of all modules, classes, 
# functions, and methods in the package.

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to any branch
on:
  push

# Set permissions for the workflow
permissions:
  contents: read  # Only read access to repository contents is needed

jobs:
  pdoc:
    name: Generate API Documentation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Set up the Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install all package dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      # Step 4: Install pdoc and generate documentation
      # The documentation is output to the artifacts/pdoc directory
      # and specifically targets the quantstats_lumi package
      - name: Install and build pdoc
        run: |
          pip install --no-cache-dir pdoc
          pdoc -o artifacts/pdoc quantstats_lumi

      # Step 5: Upload the generated documentation as a workflow artifact
      # This makes the documentation available for download from the GitHub Actions page
      # The artifact is retained for 1 day to save storage space
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: pdoc
          path: artifacts/pdoc
          retention-days: 1
